Atarraya.Tests.One/Models/Person.cs
namespace Atarraya.Tests.One.Models;
public class Person
{
    public Guid PersonId { get; set; }
    public string? FirstName { get; set; }
    public string? FatherLastName { get; set; }
    public string? MotherLastName { get; set; }
    public DateTime BirthDate { get; set; }
    public string? BirthState { get; set; }
}

Atarraya.Tests.One/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Atarraya.Tests.One.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Atarraya.Tests.One/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Atarraya.Tests.One.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Atarraya.Tests.One/Pages/People/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Atarraya.Tests.One.Constants;
using Atarraya.Tests.One.Interface;
using Atarraya.Tests.One.Interface.Commands;
using Atarraya.Tests.One.Interface.Completions;
using Atarraya.Tests.One.Interface.Rejections;
using Atarraya.Tests.One.Services;

namespace Atarraya.Tests.One.Pages.People;
public class AddModel : PageModel
{
    private PeopleService PeopleService { get; set; }
    internal OperationResult? LastResult { get; set; }

    public AddModel(PeopleService peopleService)
    {
        PeopleService = peopleService;
    }

    public void OnGet()
    {
    }

    public async Task OnPost([FromForm] string firstName,
        [FromForm] string fatherLastName,
        [FromForm] string motherLastName,
        [FromForm] DateTime birthDate,
        [FromForm] string birthState)
    {
        LastResult = await PeopleService!.AddPerson(new CreatePersonCommand
        {
            BirthDate = birthDate,
            FirstName = firstName,
            BirthState = birthState,
            FatherLastName = fatherLastName,
            MotherLastName = motherLastName
        });
    }
}

Atarraya.Tests.One/Pages/People/Index.cshtml.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Atarraya.Tests.One.Interface;
using Atarraya.Tests.One.Interface.Commands;
using Atarraya.Tests.One.Interface.Completions;
using Atarraya.Tests.One.Interface.Rejections;
using Atarraya.Tests.One.Models;
using Atarraya.Tests.One.Services;

namespace Atarraya.Tests.One.Pages.People;
public class IndexModel : PageModel
{
    private PeopleService PeopleService { get; set; }
    internal OperationResult? LastResult { get; set; }
    internal List<Person> People { get; set; }

    public IndexModel(PeopleService peopleService)
    {
        PeopleService = peopleService;
        People = new List<Person>();
    }

    public async Task OnGet()
    {
        var result = await PeopleService!.SelectPeople();
        if (result is SelectPeopleCompleted completed)
            People = completed.SelectedPeople;
    }

    public async Task OnPostDelete(Guid personId)
    {
        LastResult = await PeopleService!.DeletePerson(new DeletePersonCommand
        {
            PersonId = personId
        });
    }
}

Atarraya.Tests.One/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Atarraya.Tests.One.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Atarraya.Tests.One/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Bienvenido";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>Test One - Atarraya.</p>
</div>

Atarraya.Tests.One/Pages/People/Add.cshtml
@page "/people/add"
@model Atarraya.Tests.One.Pages.People.AddModel
@{
    ViewData["Title"] = "Nueva persona";
}

<partial name="People/_MessageViewer" model="Model.LastResult" />
<form method="post">
    <div class="mb-3">
        <label for="firstname" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="firstname" name="firstname" aria-describedby="firstnameHelp" required/>
        <div id="firstnameHelp" class="form-text">Introduce tu nombre o nombres.</div>
    </div>
    <div class="mb-3">
        <label for="fatherLastname" class="form-label">Apellido paterno</label>
        <input type="text" class="form-control" id="fatherLastname" name="fatherLastname" aria-describedby="fatherLastnameHelp" required/>
        <div id="fatherLastnameHelp" class="form-text">Introduce tu apellido paterno.</div>
    </div>
    <div class="mb-3">
        <label for="motherLastname" class="form-label">Apellido materno</label>
        <input type="text" class="form-control" id="motherLastname" name="motherLastname" aria-describedby="motherLastnameHelp" required/>
        <div id="motherLastnameHelp" class="form-text">Introduce tu apellido paterno.</div>
    </div>
    <div class="mb-3">
        <label for="birthDate" class="form-label">Fecha de nacimiento</label>
        <input type="date" class="form-control" id="birthDate" name="birthDate" aria-describedby="birthDateHelp" required/>
        <div id="birthDateHelp" class="form-text">Selecciona tu fecha de nacimiento.</div>
    </div>
    <div class="mb-3">
        <label for="birthState" class="form-label">Estado de nacimiento de nacimiento</label>
        <select class="form-control" id="birthState" name="birthState" aria-describedby="birthStateHelp" required>
            <option value='AGU'>Aguascalientes</option>
            <option value='BCN'>Baja California</option>
            <option value='BCS'>Baja California Sur</option>
            <option value='CAM'>Campeche</option>
            <option value='CHP'>Chiapas</option>
            <option value='CHH'>Chihuahua</option>
            <option value='CMXC​'>Ciudad de México</option>
            <option value='COA'>Coahuila</option>
            <option value='COL'>Colima</option>
            <option value='DUR'>Durango</option>
            <option value='GUA'>Guanajuato</option>
            <option value='GRO'>Guerrero</option>
            <option value='HID'>Hidalgo</option>
            <option value='JAL'>Jalisco</option>
            <option value='MEX'>México</option>
            <option value='MIC'>Michoacán</option>
            <option value='MOR'>Morelos</option>
            <option value='NAY'>Nayarit</option>
            <option value='NLE'>Nuevo León</option>
            <option value='OAX'>Oaxaca</option>
            <option value='PUE'>Puebla</option>
            <option value='QUE'>Querétaro</option>
            <option value='ROO'>Quintana Roo</option>
            <option value='SLP'>San Luis Potosí</option>
            <option value='SIN'>Sinaloa</option>
            <option value='SON'>Sonora</option>
            <option value='TAB'>Tabasco</option>
            <option value='TAM'>Tamaulipas</option>
            <option value='TLA'>Tlaxcala</option>
            <option value='VER'>Veracruz</option>
            <option value='YUC'>Yucatán</option>
            <option value='ZAC'>Zacatecas</option>
        </select>
        <div id="birthStateHelp" class="form-text">Selecciona tu estado de nacimiento.</div>
    </div>
    <button type="submit" class="btn btn-primary" id="save">Guardar</button>
    <button type="reset" class="btn btn-secondary">Cancelar</button>
</form>

Atarraya.Tests.One/Pages/People/Index.cshtml
@page "/people"
@model Atarraya.Tests.One.Pages.People.IndexModel
@{
    ViewData["Title"] = "Personas";
}

<partial name="People/_MessageViewer" model="Model.LastResult" />
<a asp-page="/People/Add" class="btn btn-primary"><i class="fas fa-plus"></i> Nueva persona</a>
<table id="people" class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido paterno</th>
            <th>Apellido materno</th>
            <th>Fecha de nacimiento</th>
            <th>Estado de materno</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var person in Model.People)
        {
            <tr>
                <td>@person.FirstName</td>
                <td>@person.FatherLastName</td>
                <td>@person.MotherLastName</td>
                <td>@person.BirthDate</td>
                <td>@person.BirthState</td>
                <td>
                    <form method="post" asp-page-handler="delete">
                        <input type="hidden" name="personId" value="@person.PersonId" />
                        <button class="btn btn-link text-danger"><i class="fas fa-trash"></i></button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

Atarraya.Tests.One/Pages/People/_MessageViewer.cshtml
@model Atarraya.Tests.One.Interface.OperationResult

@if (Model != null)
{
    switch (Model)
    {
        case Atarraya.Tests.One.Interface.Completions.AddPersonCompleted completed:
            <div id="result" class="alert alert-success" role="alert">
                Persona @completed.AddedPerson.PersonId creada correctamente.
            </div>
            break;

        case Atarraya.Tests.One.Interface.Rejections.PersonOperationRejected rejected:
            <div id="result" class="alert alert-danger" role="alert">
                @Messages.FromErrorCode(rejected.ErrorCode)
            </div>
            break;
    }

}

Atarraya.Tests.One/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-mx">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo uno</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="~/css/fontawesome.all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Atarraya.Tests.One.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Atarraya</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/people/index">Personas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Atarraya 
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>